name: Bundle info.json Files

on:
  schedule:
    - cron: "0 0 * * 0" # 00:00 on Sunday
  workflow_dispatch:

jobs:
  bundle-info-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: qmk/qmk_firmware
          path: qmk_firmware
      - name: Install Dependencies
        run: sudo apt-get install -y jq zip
      - name: Fetch and Bundle info.json
        run: |
          cd qmk_firmware/keyboards
          mkdir tmp_info_jsons
          counter=1
          find . -name info.json | while read file; do
            if jq -e 'has("keyboard_name")' "$file" > /dev/null && jq -e 'has("usb")' "$file" > /dev/null; then
              cp "$file" "tmp_info_jsons/info$counter.json"
              ((counter++))
            fi
          done
          cd tmp_info_jsons
          zip info_json_files.zip *
          mv info_json_files.zip $GITHUB_WORKSPACE
          cd ..
          rm -rf tmp_info_jsons
      # - name: Upload Zip File to Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: info_json_files
      #     path: info_json_files.zip
      - name: Upload Zip File to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: info_json_files.zip
          asset_name: info_json_files.zip
          tag: ${{ github.ref }}
          overwrite: true
